# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=150, verbose_name='Line 1')),
                ('apt', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apt')),
                ('city', models.CharField(default='Miami', max_length=40, verbose_name='City')),
                ('state', models.CharField(default='FL', max_length=20, verbose_name='State')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='PDF', verbose_name='PDF')),
                ('type', models.CharField(choices=[('BOTH', 'Both'), ('LEASE', 'Lease'), ('RENT', 'Rent')], default='Both', max_length=10, verbose_name='Type')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condo', to='condos.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Condo',
                'verbose_name_plural': 'Condos',
            },
        ),
    ]
