# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0002_application_condo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
