# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:01
from __future__ import unicode_literals

import condocument_settings.helpers.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0003_auto_20170314_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('BOTH', 'Both'), ('LEASE', 'Lease'), ('RENT', 'Rent')], default=condocument_settings.helpers.enum.Types('Both'), max_length=10, verbose_name='Type'),
        ),
    ]
