# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:54
from __future__ import unicode_literals

import condocument_settings.helpers.enum
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0005_auto_20170320_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='Number')),
                ('mls_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='MLS Number')),
                ('st', models.CharField(blank=True, max_length=10, null=True, verbose_name='St')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='Area')),
                ('list_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('beds', models.IntegerField(blank=True, null=True, verbose_name='Beds')),
                ('f_baths', models.IntegerField(blank=True, null=True, verbose_name='FBaths')),
                ('h_baths', models.IntegerField(blank=True, null=True, verbose_name='HBaths')),
                ('live_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Live Area')),
                ('association_fee', models.IntegerField(blank=True, null=True, verbose_name='Association Fee')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('garage_spot', models.IntegerField(blank=True, null=True, verbose_name='Garage Spots')),
                ('pool', models.BooleanField(default=False, verbose_name='Pool')),
                ('waterfront', models.BooleanField(default=False, verbose_name='Waterfront')),
                ('current_price', models.IntegerField(blank=True, null=True, verbose_name='Current Price')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry Date')),
                ('days_market', models.IntegerField(blank=True, null=True, verbose_name='Days on market')),
                ('property_type', models.CharField(choices=[('RENT', 'For rent'), ('SALE', 'For sale')], default=condocument_settings.helpers.enum.PropertyType('For rent'), max_length=10, verbose_name='Property type')),
                ('rent_period', models.IntegerField(blank=True, null=True, verbose_name='Rent Period')),
                ('furnished', models.CharField(blank=True, max_length=50, null=True, verbose_name='Furnished')),
                ('condo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='condos.Condo', verbose_name='Condo')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='PDF'),
        ),
    ]
