# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0006_auto_20170320_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='bedroomquantity',
            name='type',
            field=models.CharField(choices=[('RENT', 'For rent'), ('SALE', 'For sale')], max_length=10, verbose_name='Type'),
        ),
    ]
