# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0008_auto_20170321_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('BOTH', 'Both'), ('PURCHASE', 'Purchase'), ('RENT', 'Rent')], default='Both', max_length=10, verbose_name='Type'),
        ),
    ]
