# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0009_auto_20170321_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='st',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
    ]
