# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0010_auto_20170322_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='rent_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rent Period'),
        ),
    ]
