# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 15:13
from __future__ import unicode_literals

import condocument_settings.helpers.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='info',
            field=models.FileField(blank=True, null=True, upload_to='info', verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(blank=True, choices=[('CONDO', 'Condo'), ('USER', 'User')], default=condocument_settings.helpers.enum.ContentType('Condo'), max_length=10, null=True, verbose_name='Type'),
        ),
    ]
