# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170314_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
