# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170320_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[people.models.validate_ssn], verbose_name='SSN'),
        ),
    ]
