# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20170429_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID or License'),
        ),
    ]
