# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170429_2058'),
        ('people', '0005_auto_20170508_1549'),
    ]

    operations = [
    ]
